version: '3.9'

services:
  postgres:
    image: postgres
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - network
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: 'adminer'
    depends_on:
      - postgres
    networks:
      - network
    ports:
      - 8080:8080
    restart: always

networks:
  network:
    driver: bridge
